---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_inventory: ./hosts
  ansible_sudo: true
#  ansible_verbose: true
#  ansible_verbosity: 2
  playbook: docker-registry.yml
  roles_path: ./roles/

verifier: 
  name: inspec

platforms:
  - name: registry
    driver_plugin: vagrant
    driver_config:
      box: bento/centos-7.4
      network:
      - ['private_network', {ip: '192.168.3.3'}]

suites:
  - name: docker-registry
    verifier:
      inspec_tests:
        - tests

# Workaround to avoid 'SCP upload failed (open failed (1))'.
transport:
  max_ssh_sessions: 6
  