---
galaxy_info:
  author: Artem Shorokhov
  description: Set up private Docker registry behind nginx SSl proxy.
  license: BSD
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags:
    - Docker

dependencies: []
